In [ ]:
print("Started with Numpy")
# Numpy perform operations faster
# Stores val in contiguous memory locations
# SIMD vector processing,effective cache utilization
# It's kind of MATLAB replacement
# useful inplotting,backend(core component for pandas,connect 4,digital photography)
# machine learning

Started with Numpy


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [50]:
# initialize an array
import numpy as np

arr = np.array([1,2,3,4], dtype='int32')
arr2 =np.array(([1,2,3],[5,6,7]))
print(arr,arr2)
arr.ndim #returns dimension
arr2.ndim

print(type(arr))
print(arr.shape,arr2.shape) #get shape (1d - axis 0,2d-axis 0 and axis 1,3d - axis 0,axis 1,axis 2)
print(arr.dtype,arr.itemsize,arr.nbytes) #get the type , itemsize - returns the bytes size ,nbytes - returns toral size



[1 2 3 4] [[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
(4,) (2, 3)
int32 4 16


In [56]:
a = np.array(([1,2,3,4,5,6,7],[8,9,10,11,12,13,14]))
print(a)
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# inbuilt functions in numpy

arr2 = np.zeros((2,2)) ## creates an array of all zeros
arr3 = np.ones((3,3))   ## creates an array of all ones
arr4 = np.full((2,2),8) ## creates a constant array
z = np.full_like(a,5)
arr5 = np.eye(3)   ## creates a 3x3 identity matrix
r = np.random.randint(5,7,size=(2,2))
arr6 = np.random.random((2,3)) ##creates an array filled with random values
i = np.identity(3)

temp = np.array([[1,2,3]])
r1 = np.repeat(temp,3,axis=0)




print(arr2 ,"zeros")
print(arr3,"ones")
print(arr4,"constant")
print(arr5,"identity matrix")
print(arr6,r,"random array")
print(z,"full_like")
print(i,"identity")
print(r1,"repeat array")





[[0. 0.]
 [0. 0.]] zeros
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] ones
[[8 8]
 [8 8]] constant
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] identity matrix
[[8.29559160e-01 1.62514811e-01 9.51707307e-01]
 [9.33981583e-01 7.15582987e-01 2.11770331e-04]] [[6 5]
 [6 5]] random array
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]] full_like
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] identity
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [81]:
# recreate a array picture using np.array and functions
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 8 0 1
# 1 0 0 0 1
# 1 1 1 1 1

a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 8

print(b)
a [1:-1,1:-1] = b
print(a)

[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [87]:
# careful while copying array
a = np.array([1,2,3])
# b = a
# b[2] = 88
# print(b)
# print(a) here b is also pointing to where a is so when modify it will change the content of a 

b = a.copy()
b[2] = 88
print(a)
print(b)

[1 2 3]
[ 1  2 88]


In [31]:
# Array Indexing
# When you index into numpy arrays using slicing, 
# the resulting array view will always be a subarray 
# of the original array.

a = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a)

# slicing to pull out few value sform above array 
# returns first 2 rows and col 1,2
b = a[:2,1:3]
print(b)

# Integer Array indexing
# In contrast, integer array indexing allows you 
# to construct arbitrary arrays using the data 
# from another array.
print(a[[1,2],[1,0]])
# above is same as below
print(np.array([a[1,1],a[2,0]]))
# When using integer array indexing, you can reuse the same
# element from the source array:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[5 7]
[5 7]


In [33]:
# One useful trick with integer array indexing is selecting or mutating 
# one element from each row of a matrix

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0,2,0,1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [88]:
# Boolean array indexing: 
# Boolean array indexing lets you pick out arbitrary elements
# of an array.
# Frequently this type of indexing is used to 
# select the elements of an array that satisfy some condition.

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [96]:
# Mathematics 

a = np.array([1,2,3,4])
add = a + 2
sub = a-1
mul = a*10
div = a/2
sin = np.sin(a) # can perform other operations

print(a)
print(add)
print(sub)
print(mul)
print(div)
print(sin)


[1 2 3 4]
[3 4 5 6]
[0 1 2 3]
[10 20 30 40]
[0.5 1.  1.5 2. ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [100]:
# ----- Statistics

a = np.array([1,2,3])
print(np.min(a))
print(np.max(a))
print(np.sum(a))



1
3
6
