In [1]:
print("Started with Numpy")
# Numpy perform operations faster
# Stores val in contiguous memory locations
# SIMD vector processing,effective cache utilization
# It's kind of MATLAB replacement
# useful inplotting,backend(core component for pandas,connect 4,digital photography)
# machine learning

Started with Numpy


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [50]:
# initialize an array
import numpy as np

arr = np.array([1,2,3,4], dtype='int32')
arr2 =np.array(([1,2,3],[5,6,7]))
print(arr,arr2)
arr.ndim #returns dimension
arr2.ndim

print(type(arr))
print(arr.shape,arr2.shape) #get shape (1d - axis 0,2d-axis 0 and axis 1,3d - axis 0,axis 1,axis 2)
print(arr.dtype,arr.itemsize,arr.nbytes) #get the type , itemsize - returns the bytes size ,nbytes - returns toral size



[1 2 3 4] [[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
(4,) (2, 3)
int32 4 16


In [56]:
a = np.array(([1,2,3,4,5,6,7],[8,9,10,11,12,13,14]))
print(a)
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [73]:
# inbuilt functions in numpy

arr2 = np.zeros((2,2)) ## creates an array of all zeros
arr3 = np.ones((3,3))   ## creates an array of all ones
arr4 = np.full((2,2),8) ## creates a constant array
z = np.full_like(a,5)
arr5 = np.eye(3)   ## creates a 3x3 identity matrix
r = np.random.randint(5,7,size=(2,2))
arr6 = np.random.random((2,3)) ##creates an array filled with random values
i = np.identity(3)

temp = np.array([[1,2,3]])
r1 = np.repeat(temp,3,axis=0)




print(arr2 ,"zeros")
print(arr3,"ones")
print(arr4,"constant")
print(arr5,"identity matrix")
print(arr6,r,"random array")
print(z,"full_like")
print(i,"identity")
print(r1,"repeat array")





[[0. 0.]
 [0. 0.]] zeros
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] ones
[[8 8]
 [8 8]] constant
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] identity matrix
[[8.29559160e-01 1.62514811e-01 9.51707307e-01]
 [9.33981583e-01 7.15582987e-01 2.11770331e-04]] [[6 5]
 [6 5]] random array
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]] full_like
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] identity
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [81]:
# recreate a array picture using np.array and functions
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 8 0 1
# 1 0 0 0 1
# 1 1 1 1 1

a = np.ones((5,5))
b = np.zeros((3,3))
b[1,1] = 8

print(b)
a [1:-1,1:-1] = b
print(a)

[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [87]:
# careful while copying array
a = np.array([1,2,3])
# b = a
# b[2] = 88
# print(b)
# print(a) here b is also pointing to where a is so when modify it will change the content of a 

b = a.copy()
b[2] = 88
print(a)
print(b)

[1 2 3]
[ 1  2 88]


In [31]:
# Array Indexing
# When you index into numpy arrays using slicing, 
# the resulting array view will always be a subarray 
# of the original array.

a = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a)

# slicing to pull out few value sform above array 
# returns first 2 rows and col 1,2
b = a[:2,1:3]
print(b)

# Integer Array indexing
# In contrast, integer array indexing allows you 
# to construct arbitrary arrays using the data 
# from another array.
print(a[[1,2],[1,0]])
# above is same as below
print(np.array([a[1,1],a[2,0]]))
# When using integer array indexing, you can reuse the same
# element from the source array:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[5 7]
[5 7]


In [33]:
# One useful trick with integer array indexing is selecting or mutating 
# one element from each row of a matrix

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0,2,0,1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [88]:
# Boolean array indexing: 
# Boolean array indexing lets you pick out arbitrary elements
# of an array.
# Frequently this type of indexing is used to 
# select the elements of an array that satisfy some condition.

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [96]:
# Mathematics 

a = np.array([1,2,3,4])
add = a + 2
sub = a-1
mul = a*10
div = a/2
sin = np.sin(a) # can perform other operations

print(a)
print(add)
print(sub)
print(mul)
print(div)
print(sin)


[1 2 3 4]
[3 4 5 6]
[0 1 2 3]
[10 20 30 40]
[0.5 1.  1.5 2. ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [101]:
# ----- Statistics

a = np.array([1,2,3])
print(np.min(a))
print(np.max(a))
print(np.sum(a))



1
3
6


In [117]:
# Boolean Masking 
a = np.array([19,24,30,445,128,29])
a[a > 20]

mask = a > 20
print(mask)

# modifying elements in place
a[a>30] = 100
print(a)

# Apply multiple condition
mask_con = (a > 20) & (a<200)
print(a[mask_con])

# Use np.sum() on a boolean array (where True is treated as 1 and False as 0) to count occurrences.
mask_sum = np.sum(a > 20)
print(mask_sum)

# The np.where(condition, x, y) function provides an if-else operation for arrays. 
# It returns an array of the same shape, 
# with elements from x where the condition is True, and elements from y where False.
mask_where = np.where(a > 30,"above 30",a)
print(mask_where)

print(np.any(a))


[False  True  True  True  True  True]
[ 19  24  30 100 100  29]
[ 24  30 100 100  29]
5
['19' '24' '30' 'above 30' 'above 30' '29']
True


In [122]:
#  Vectorization
#  - performing mathematical operations on entire array

# ex-1
arr = np.array([5,10,20,30,40,50])
arr2 = np.array([100,200,300,400,500,600])
num = 100

res = arr +num
res2 = arr +arr2
print(res)
print(res2)

# using vectorize() function for reuse on different arr
# used the vectorize() fn to vectorize the sqr_num() function
a = np.array([-1,0,2,5,6,-5])
def sqr_num(x):
    if x <= 0:
        return "negative"
    else:
        return x**2
    
vect_fn = np.vectorize(sqr_num)
result = vect_fn(a)
print(result)    

[105 110 120 130 140 150]
[105 210 320 430 540 650]
['negative' 'negative' '4' '25' '36' 'negative']


In [124]:
### Axis Parameter
# axis 0 is for vertical(row) and axis 1 is for horizontal(col)
# 1D Array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:\n", arr_1d)            # Output: [1 2 3 4]
print("Sum (Axis 0):", np.sum(arr_1d, axis=0))  # Output: 10 (Sum of all elements)


# 2D Array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("\n2D Array:\n", arr_2d)             # Output: [[1 2 3]
                                          #          [4 5 6]]

print("Sum along rows (Axis 0):", np.sum(arr_2d, axis=0))  # Output: [5 7 9]
print("Sum along columns (Axis 1):", np.sum(arr_2d, axis=1))  # Output: [6 15]
print("Overall Sum:", np.sum(arr_2d))     # Output: 21 (Sum of all elements)


# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

print("\n3D Array:\n", arr_3d)            # Output: [[[1 2]
                                          #          [3 4]]
                                          #         [[5 6]
                                          #          [7 8]]]
print("Sum along depth (Axis 0):\n", np.sum(arr_3d, axis=0))  
# Output: [[ 6  8]
#          [10 12]]
print("Sum along rows (Axis 1):\n", np.sum(arr_3d, axis=1))  
# Output: [[ 4  6]
#          [12 14]]
print("Sum along columns (Axis 2):\n", np.sum(arr_3d, axis=2))  
# Output: [[ 3  7]
#          [11 15]]

1D Array:
 [1 2 3 4]
Sum (Axis 0): 10

2D Array:
 [[1 2 3]
 [4 5 6]]
Sum along rows (Axis 0): [5 7 9]
Sum along columns (Axis 1): [ 6 15]
Overall Sum: 21

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Sum along depth (Axis 0):
 [[ 6  8]
 [10 12]]
Sum along rows (Axis 1):
 [[ 4  6]
 [12 14]]
Sum along columns (Axis 2):
 [[ 3  7]
 [11 15]]


In [1]:
# Normalization
# Normalization scales data to a common range so features are comparable and models behave correctly.
# | Type    | Range         | When to use                |
# | ------- | ------------- | -------------------------- |
# | Min–Max | 0–1           | Scores, marks, percentages |
# | Z-score | Mean=0, Std=1 | ML models                  |

# | Use case              | Method            |
# | --------------------- | ----------------- |
# | Marks / percentages   | Min–Max           |
# | ML models             | Z-score           |
# | Probability-like data | Row normalization |


# 1️⃣ Min–Max Normalization (0 to 1) ✅ MOST COMMON

    # forula -->  x′=max−min/x−min​
    # ✔ Preserves relative ranking
    # ✔ Output between 0 and 1

# 2️⃣ Z-score Normalization (Standardization) ⭐ ML-FRIENDLY

    # forula -->  x′=x-mean/std
    # ✔ Mean = 0
    # ✔ Std = 1
    # ✔ Handles outliers better

In [4]:
# ---- Mean
# When to use: When you want the typical value and your data doesn't have extreme outliers.

import numpy as np

data = np.array([10, 20, 30, 40, 50])
mean = np.mean(data)  # Returns 30

# Best for: Normally distributed data, calculating totals divided by count (like average salary, average temperature).
# Watch out: Sensitive to outliers. If you have [10, 20, 30, 40, 1000], the mean is 220, which doesn't represent most values well.

In [5]:
# ----median
# When to use: When you have outliers or skewed data.

pythondata = np.array([10, 20, 30, 40, 1000])
median = np.median(data)  # Returns 30

# Best for: Income data, house prices, or any dataset with extreme values. The median isn't affected by that 1000 outlier.
# How it works: Sorts values and picks the middle one (or average of two middle values if even count).

In [ ]:
# ----mode
# When to use: When you want the most common value, especially for categorical or discrete data.
# pythonfrom scipy import stats  # NumPy doesn't have mode, use scipy

data = np.array([1, 2, 2, 3, 3, 3, 4])
mode = stats.mode(data, keepdims=True)  # Returns 3

# Best for: Survey responses, product ratings, most common shoe size, voting results.
# Watch out: Can have multiple modes or no meaningful mode in continuous data.