In [ ]:
print("Started with Numpy")

Started with Numpy


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
# inbuilt functions in numpy

arr2 = np.zeros((2,2)) ## creates an array of all zeros
arr3 = np.ones((3,3))   ## creates an array of all ones
arr4 = np.full((2,2),8) ## creates a constant array
arr5 = np.eye(3)   ## creates a 3x3 identity matrix
arr6 = np.random.random((2,3)) ##creates an array filled with random values
print(arr2 ,"zeros")
print(arr3,"ones")
print(arr4,"constant")
print(arr5,"identity matrix")
print(arr6,"random array")



[[0. 0.]
 [0. 0.]] zeros
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] ones
[[8 8]
 [8 8]] constant
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] identity matrix
[[0.26104412 0.84737854 0.97713502]
 [0.91788128 0.84113173 0.71805235]] random array


In [31]:
# Array Indexing
# When you index into numpy arrays using slicing, 
# the resulting array view will always be a subarray 
# of the original array.

a = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a)

# slicing to pull out few value sform above array 
# returns first 2 rows and col 1,2
b = a[:2,1:3]
print(b)

# Integer Array indexing
# In contrast, integer array indexing allows you 
# to construct arbitrary arrays using the data 
# from another array.
print(a[[1,2],[1,0]])
# above is same as below
print(np.array([a[1,1],a[2,0]]))
# When using integer array indexing, you can reuse the same
# element from the source array:

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[5 7]
[5 7]


In [33]:
# One useful trick with integer array indexing is selecting or mutating 
# one element from each row of a matrix

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0,2,0,1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [34]:
# Boolean array indexing: 
# Boolean array indexing lets you pick out arbitrary elements
# of an array.
# Frequently this type of indexing is used to 
# select the elements of an array that satisfy some condition.

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2]) 

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
