In [7]:
import numpy as np

np.random.seed(42)

# created random marks for 20 students in the range(50 - 100)
# 4 subjects - math,history,science,IT
scores = np.random.randint(50,101,size=(20,4))
print(scores)

# return the shape,dimension,size
print(scores.shape)
print(scores.size)
print(scores.ndim)

[[ 88  78  64  92]
 [ 57  70  88  68]
 [ 72  60  60  73]
 [ 85  89  73  52]
 [ 71  51  73  93]
 [ 79  87  51  70]
 [ 82  61  71  93]
 [ 74  98  76  91]
 [ 77  65  64  96]
 [100  93  52  86]
 [100  56  70  58]
 [ 88  67  53  74]
 [ 63  99  58  75]
 [ 51  69  77  96]
 [ 56  93  57  96]
 [ 84  63  66  85]
 [ 99  89  53  51]
 [ 55  91  53  78]
 [ 67  75  93  83]
 [ 59  85  63  80]]
(20, 4)
80
2


In [22]:
# return top 5 and lats 5 result
top_5 = scores[:6]
last_5 = scores[-5:]
print("Scores for first 5",top_5)
print("Scores for last 5",last_5)

# retrieve marks for specific sub
math_marks = scores[:,0]
IT_marks = scores[:,-1]

avg_math = np.mean(math_marks)
avg_IT = np.mean(IT_marks)

# used axis 
# axis=0 → collapse rows → keep columns
# axis=1 → collapse columns → keep rows
avg_all = np.mean(scores,axis=0)
print("Math scores all",math_marks)
print("IT scores all",IT_marks)

print("Average of maths",avg_math)
print("Average of IT",avg_IT)
print("Average of all subjects",avg_all)


Scores for first 5 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]
 [79 87 51 70]]
Scores for last 5 [[84 63 66 85]
 [99 89 53 51]
 [55 91 53 78]
 [67 75 93 83]
 [59 85 63 80]]
Math scores all [ 88  57  72  85  71  79  82  74  77 100 100  88  63  51  56  84  99  55
  67  59]
IT scores all [92 68 73 52 93 70 93 91 96 86 58 74 75 96 96 85 51 78 83 80]
Average of maths 75.35
Average of IT 79.5
Average of all subjects [75.35 76.95 65.75 79.5 ]


In [29]:
# Total scores of each student 
total_scores = scores.sum(axis=1)
print(total_scores)

# using python
for ind,res in enumerate(total_scores,start=1):
    print(f"{ind}. {res}")

# using numpy
indexed_score = np.column_stack((np.arange(1,len(total_scores)+1),(total_scores)))
print(indexed_score)

[322 283 265 299 288 287 307 339 302 331 284 282 295 293 302 298 292 277
 318 287]
1. 322
2. 283
3. 265
4. 299
5. 288
6. 287
7. 307
8. 339
9. 302
10. 331
11. 284
12. 282
13. 295
14. 293
15. 302
16. 298
17. 292
18. 277
19. 318
20. 287
[[  1 322]
 [  2 283]
 [  3 265]
 [  4 299]
 [  5 288]
 [  6 287]
 [  7 307]
 [  8 339]
 [  9 302]
 [ 10 331]
 [ 11 284]
 [ 12 282]
 [ 13 295]
 [ 14 293]
 [ 15 302]
 [ 16 298]
 [ 17 292]
 [ 18 277]
 [ 19 318]
 [ 20 287]]


In [34]:
# Performance Comparison
math_vs_history = scores[:,0]>scores[:,1]
print(math_vs_history)

# count students
total_stud = np.count_nonzero(math_vs_history)
print("Students math marks > history marks -->",total_stud)

[ True False  True False  True False  True False  True  True  True  True
 False False False  True  True False False False]
Students math marks > history marks --> 10


In [51]:
# normalization
# It’s a performance profile, not just marks.

# column wise normalization
max_nor =scores.max(axis=0)
min_nor = scores.min(axis=0)
normalized_score = (scores-min_nor)/(max_nor-min_nor)
readable = np.round(normalized_score,2)
print(normalized_score)
print(normalized_score[:,0])
print(readable)




[[0.75510204 0.5625     0.30952381 0.91111111]
 [0.12244898 0.39583333 0.88095238 0.37777778]
 [0.42857143 0.1875     0.21428571 0.48888889]
 [0.69387755 0.79166667 0.52380952 0.02222222]
 [0.40816327 0.         0.52380952 0.93333333]
 [0.57142857 0.75       0.         0.42222222]
 [0.63265306 0.20833333 0.47619048 0.93333333]
 [0.46938776 0.97916667 0.5952381  0.88888889]
 [0.53061224 0.29166667 0.30952381 1.        ]
 [1.         0.875      0.02380952 0.77777778]
 [1.         0.10416667 0.45238095 0.15555556]
 [0.75510204 0.33333333 0.04761905 0.51111111]
 [0.24489796 1.         0.16666667 0.53333333]
 [0.         0.375      0.61904762 1.        ]
 [0.10204082 0.875      0.14285714 1.        ]
 [0.67346939 0.25       0.35714286 0.75555556]
 [0.97959184 0.79166667 0.04761905 0.        ]
 [0.08163265 0.83333333 0.04761905 0.6       ]
 [0.32653061 0.5        1.         0.71111111]
 [0.16326531 0.70833333 0.28571429 0.64444444]]
[0.75510204 0.12244898 0.42857143 0.69387755 0.40816327 0.5

In [53]:
# row wise normalization
row_sum = scores.sum(axis=1, keepdims=True)
row_normalized = scores / row_sum
print(row_normalized)

[[0.27329193 0.24223602 0.19875776 0.28571429]
 [0.20141343 0.24734982 0.31095406 0.24028269]
 [0.27169811 0.22641509 0.22641509 0.2754717 ]
 [0.28428094 0.29765886 0.24414716 0.17391304]
 [0.24652778 0.17708333 0.25347222 0.32291667]
 [0.27526132 0.30313589 0.17770035 0.24390244]
 [0.26710098 0.19869707 0.23127036 0.3029316 ]
 [0.21828909 0.28908555 0.22418879 0.26843658]
 [0.25496689 0.21523179 0.21192053 0.31788079]
 [0.3021148  0.28096677 0.1570997  0.25981873]
 [0.35211268 0.1971831  0.24647887 0.20422535]
 [0.31205674 0.23758865 0.18794326 0.26241135]
 [0.21355932 0.33559322 0.19661017 0.25423729]
 [0.17406143 0.23549488 0.26279863 0.32764505]
 [0.18543046 0.30794702 0.18874172 0.31788079]
 [0.28187919 0.2114094  0.22147651 0.2852349 ]
 [0.3390411  0.30479452 0.18150685 0.17465753]
 [0.19855596 0.32851986 0.19133574 0.28158845]
 [0.21069182 0.23584906 0.29245283 0.26100629]
 [0.20557491 0.29616725 0.2195122  0.27874564]]


In [56]:
# average for all subjects
subjects = ["Math", "History", "Science", "IT"]

for i, subj in enumerate(subjects):
    print(subj, "avg:", scores[:, i].mean())


Math avg: 75.35
History avg: 76.95
Science avg: 65.75
IT avg: 79.5


In [67]:
rank_normal = normalized_score.sum(axis=1)
print(rank_normal)

# np.argsort(array) returns the indices that would sort the array.
# It does not return the sorted values itself.
# It returns an array of positions (indices).

ranks = np.argsort(-rank_normal) 
print(ranks)

for rank,stud_ind in enumerate(np.argsort(ranks),start=1):
    print(f"{rank} student {stud_ind+1} Score {rank_normal[stud_ind]: .2f} ")


# top performer

top_performer = np.argmax(normalized_score,axis=0)
subjects = ["Math", "History", "Science", "IT"]
print("Top Performer Subject")
for subj,stud_ind in enumerate(top_performer):
    print(f"Subject {subjects[subj]} : Student {stud_ind+1}")

[2.53823696 1.77701247 1.31924603 2.03157596 1.86530612 1.74365079
 2.2505102  2.93268141 2.13180272 2.6765873  1.71210317 1.64716553
 1.94489796 1.99404762 2.11989796 2.0361678  1.81887755 1.56258503
 2.53764172 1.80175737]
[ 7  9  0 18  6  8 14 15  3 13 12  4 16 19  1  5 10 11 17  2]
1 student 3 Score  1.32 
2 student 15 Score  2.12 
3 student 20 Score  1.80 
4 student 9 Score  2.13 
5 student 12 Score  1.65 
6 student 16 Score  2.04 
7 student 5 Score  1.87 
8 student 1 Score  2.54 
9 student 6 Score  1.74 
10 student 2 Score  1.78 
11 student 17 Score  1.82 
12 student 18 Score  1.56 
13 student 11 Score  1.71 
14 student 10 Score  2.68 
15 student 7 Score  2.25 
16 student 8 Score  2.93 
17 student 13 Score  1.94 
18 student 19 Score  2.54 
19 student 4 Score  2.03 
20 student 14 Score  1.99 
Top Performer Subject
Subject Math : Student 10
Subject History : Student 13
Subject Science : Student 19
Subject IT : Student 9
